# Generated by Django 5.2.3 on 2025-09-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
    ]
