# Generated by Django 5.2.3 on 2025-09-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_uploadedfile_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='salt',
            field=models.BinaryField(default=b''),
        ),
    ]
