# Generated by Django 5.2.3 on 2025-09-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_uploadedfile_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='salt',
            field=models.BinaryField(null=True),
        ),
    ]
