# Generated by Django 5.2.3 on 2025-09-27 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_uploadedfile_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='salt',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
